# -*- coding: utf-8 -*-
"""pendulum_a2c_online.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NsMuJ97xJ1s2IJ5yuBKvvePEQNzOBmZ
"""

import os

import torch.distributions.constraints
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

import numpy as np
import torch
from torch import nn
from torch.nn import functional as F
import matplotlib.pyplot as plt
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm

from Environment import AstEnv
from DataPreprocessing import DataPreProcessing


def mish(input):
    return input * torch.tanh(F.softplus(input))

class Mish(nn.Module):
    def __init__(self): super().__init__()
    def forward(self, input): return mish(input)

# helper function to convert numpy arrays to tensors
def t(x):
    x = np.array(x) if not isinstance(x, np.ndarray) else x
    return torch.from_numpy(x).float()

class Actor(nn.Module):
    def __init__(self, state_dim, n_actions, hidden_size=256, activation=nn.Tanh, prec=5):
        super().__init__()
        self.n_actions = n_actions
        self.prec = prec
        self.model = nn.Sequential(
            nn.Linear(state_dim, hidden_size),
            activation(),
            nn.Dropout(),
            nn.Linear(hidden_size, hidden_size),
            activation(),
            nn.Dropout(),
            nn.Linear(hidden_size, hidden_size),
            activation(),
            nn.Dropout(),
            nn.Linear(hidden_size, hidden_size),
            activation(),
            nn.Dropout(),
            nn.Linear(hidden_size, n_actions)
        )

        logstds_param = nn.Parameter(torch.full((n_actions,), 0.1))
        self.register_parameter("logstds", logstds_param)

    def forward(self, X):
        means = self.model(X)
        stds = torch.clamp(self.logstds.exp(), 1e-3, 50)

        #if not torch.is_tensor(self.prec):
        #    self.prec = self.prec*torch.ones_like(means)
        return torch.distributions.Normal(means, stds)
    
## Critic module
class Critic(nn.Module):
    def __init__(self, state_dim, hidden_size=256, activation=nn.Tanh):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(state_dim, hidden_size),
            activation(),
            nn.Dropout(),
            nn.Linear(hidden_size, hidden_size),
            activation(),
            nn.Dropout(),
            nn.Linear(hidden_size, hidden_size),
            activation(),
            nn.Dropout(),
            nn.Linear(hidden_size, hidden_size),
            activation(),
            nn.Dropout(),
            nn.Linear(hidden_size, 1),
        )

    def forward(self, X):
        return self.model(X)

class NNBlender(nn.Module):
    def __init__(self, NN_list, blend_boundary, blend_width):
        super().__init__()
        self.NN_list = NN_list
        self.blend_boundary = blend_boundary
        self.blend_width = blend_width
        self.NN_num = len(blend_boundary) + 1
        self.blend_coefs = np.zeros(self.NN_num)
        self.blend_coefs[self.blend_coefs.shape[0]//2] = 1
    
    def forward(self, X, blend_coefs=None):
        if blend_coefs != None:
            self.blend_coefs = t(blend_coefs)
        res = 0
        for i in range(self.NN_num):
            res = res + self.blend_coefs[i]*self.NN_list[i](X)
        return res
    
    def set_blend_coef(self, reward):
        for i in range(self.NN_num-1):
            if i == 0:
                if reward < self.blend_boundary[0] - self.blend_width:
                    self.blend_coefs[:] = 0
                    self.blend_coefs[0] == 1
                    return
            else:
                if reward >= self.blend_boundary[i-1] + self.blend_width and reward < self.blend_boundary[i] - self.blend_width:
                    self.blend_coefs[:] = 0
                    self.blend_coefs[i] = 1
                    return
            
            if reward >= self.blend_boundary[i] - self.blend_width and reward < self.blend_boundary[i] + self.blend_width:
                self.blend_coefs[:] = 0
                self.blend_coefs[i] = 0.5 - 0.5*(reward - self.blend_boundary[i])/self.blend_width
                self.blend_coefs[i+1] = 0.5 + 0.5*(reward - self.blend_boundary[i])/self.blend_width
                return

            if i == self.NN_num-2:
                if reward >= self.blend_boundary[self.NN_num-2] + self.blend_width:
                    self.blend_coefs[:] = 0
                    self.blend_coefs[self.NN_num-2] = 1
                    return
        raise NotImplementedError("NN Blending error : wrong region")


def discounted_rewards(rewards, dones, gamma):
    ret = 0
    discounted = []
    for reward, done in zip(rewards[::-1], dones[::-1]):
        ret = reward + ret * gamma * (1-done)
        discounted.append(ret)

    return discounted[::-1]

def process_memory(memory, gamma=0.99, discount_rewards=True):
    actions = []
    states = []
    next_states = []
    rewards = []
    dones = []
    blend_coefs_s = []

    for action, reward, state, next_state, done, blend_coefs in memory:
        actions.append(action)
        rewards.append(reward)
        states.append(state)
        next_states.append(next_state)
        dones.append(done)
        blend_coefs_s.append(blend_coefs)

    if discount_rewards:
        if False and dones[-1] == 0:
            rewards = discounted_rewards(rewards + [last_value], dones + [0], gamma)[:-1]
        else:
            rewards = discounted_rewards(rewards, dones, gamma)

    actions = t(actions).view(-1, 1)
    states = t(states)
    next_states = t(next_states)
    rewards = t(rewards).view(-1, 1)
    dones = t(dones).view(-1, 1)
    return actions, rewards, states, next_states, dones, blend_coefs_s

def clip_grad_norm_(module, max_grad_norm):
    nn.utils.clip_grad_norm_([p for g in module.param_groups for p in g["params"]], max_grad_norm)

class A2CLearner():
    def __init__(self, actor:NNBlender, critic:NNBlender, gamma=0.9, entropy_beta=0,
                 actor_lr=4e-4, critic_lr=4e-3, max_grad_norm=0.5):
        self.gamma = gamma
        self.max_grad_norm = max_grad_norm
        self.actor = actor
        self.critic = critic
        self.entropy_beta = entropy_beta
        self.actor_optim = torch.optim.Adam(actor.parameters(), lr=actor_lr)
        self.critic_optim = torch.optim.Adam(critic.parameters(), lr=critic_lr)

    def learn(self, memory, steps, discount_rewards=True):
        actions, rewards, states, next_states, dones, blend_coefs_s = process_memory(memory, self.gamma, discount_rewards)

        if not discount_rewards:
            td_target = rewards
        else:
            td_target = rewards + self.gamma*self.critic(next_states)*(1-dones)
        value = self.critic(states)
        advantage = td_target - value

        # actor
        norm_dists = self.actor(states)
        actions = actions.reshape(-1, 4)
        logs_probs = norm_dists.log_prob(actions)
        entropy = norm_dists.entropy().mean()

        actor_loss = (-logs_probs*advantage.detach()).mean() - entropy*self.entropy_beta
        self.actor_optim.zero_grad()
        actor_loss.backward()

        clip_grad_norm_(self.actor_optim, self.max_grad_norm)
        self.actor_optim.step()

        # critic
        critic_loss = F.mse_loss(td_target, value)
        self.critic_optim.zero_grad()
        critic_loss.backward()
        clip_grad_norm_(self.critic_optim, self.max_grad_norm)
        self.critic_optim.step()

class Runner():
    def __init__(self, env:AstEnv, actor:NNBlender, prec = 5):
        self.env = env
        self.actor = actor
        self.state = None
        self.done = True
        self.passed = False
        self.all_done = False
        self.reward_past = None
        self.steps = 0
        self.episode_reward = 0
        self.episode_rewards = []
        self.prec = prec

    def reset(self, passed):
        self.episode_reward = 0
        self.done = False
        self.passed = False
        self.state = self.env.reset(passed)
        self.reward_past = None

    def run(self, max_steps, data_num, et, reward_lists, memory=None):
        reward_list = reward_lists[0]
        max_reward_list = reward_lists[1]

        prec = self.prec
        R_cut_low = 0.25 #0.01 #0.25
        R_cut_high = 1 #0.15
        actions_space_low = [-prec, -prec, -prec, -prec]
        actinos_space_high = [prec, prec, prec, prec]

        if not memory: memory = []

        max_reward = -9e+8
        show_bool = True
        for k in range(max_steps):
            if self.all_done:
                print(" SUCCESSED in CURRENT ENV")
                print(" episode:", len(self.episode_rewards), ", episode reward:", self.episode_reward)
                self.env.show()
                break

            if self.done:
                self.reset(self.passed)

            dists = self.actor(t(self.state))
            actions = dists.sample().detach().data.numpy()
            #print(actions)
            actions[:-2] = actions[:-2] - actions[:-2]//1
            actions[-2:] = np.clip(actions[-2:], [-prec, -prec], [prec, prec])
            actions[2] = (actions[2]+prec)/(2*prec)
            actions[3] = (actions[3]+prec)*(R_cut_high-R_cut_low)/(2*prec) + R_cut_low

            next_state, reward, self.done, info = self.env.step(actions)
            if self.reward_past == None:
                self.reward_past = reward
            self.passed = info[0]
            self.all_done = info[1]
            self.actor.set_blend_coef(reward)
            memory.append((actions, reward, self.state, next_state, self.done, self.actor.blend_coefs))

            self.state = next_state
            self.steps += 1
            #self.episode_reward += reward
            #self.episode_reward += (reward - k*2)
            self.episode_reward += (reward - self.reward_past)*5 + reward
            self.reward_past = reward

            max_reward = max(max_reward, reward)
            if k%8 == 0:
                print("Reward : {:7.5g}".format(max_reward), end='')
                print(" | actions :", actions, end='')
                print(" | blending :", self.actor.blend_coefs)
                max_reward = -9e+8
                show_bool = True

            if reward > 20 and show_bool:
                print("show_passed : "+str(reward)+" | obs_lc_num : "+str(self.env.obs_lc_num))
                self.env.show(str(data_num)+"_"+str(et)+"_"+str(k)+"_"+str(int(reward*100)/100)+"_"+"0306ast.png")
                plt.close()
                show_bool = False

            if self.done:
                if self.passed:
                    print("show_passed : "+str(reward)+" | obs_lc_num : "+str(self.env.obs_lc_num))
                    self.env.show(str(data_num)+"_"+str(et)+"_"+str(k)+"_"+str(int(reward*100)/100)+"_"+"0306ast.png")
                    plt.close()
                    break    
                self.episode_rewards.append(self.episode_reward)
                max_reward_list.append(max_reward)
                if len(self.episode_rewards) % 10 == 0:
                    print(" episode:", len(self.episode_rewards), ", episode reward:", self.episode_reward)
                
        reward_list = reward_list + self.episode_rewards
        return memory, reward, (reward_list, max_reward_list)



l_max = 8
merge_num = 3
N_set = (40, 20)
lightcurve_unit_len = 100
data_path = "C:/Users/dlgkr/OneDrive/Desktop/code/astronomy/asteroid_AI/data/data_total.npz"
model_save_path = "C:/Users/dlgkr/OneDrive/Desktop/code/astronomy/asteroid_AI/checkpoints/"

dataPP = DataPreProcessing(data_path=data_path)
dataPP.X_total = torch.concat((dataPP.X_total[:, :100], dataPP.X_total[:, -9:]), dim=-1)
dataPP.Y_total = dataPP.Y_total[:, 0:(l_max+1)**2]
dataPP.coef2R(dataPP.Y_total, l_max=l_max, N_set=N_set)
dataPP.merge(merge_num=merge_num, ast_repeat_num=10, lc_len=lightcurve_unit_len, dupl_ratio=0.01)
dataPP.X_total = dataPP.X_total.numpy()
dataPP.Y_total = dataPP.Y_total.numpy()
X_total, _, y_total, _ = dataPP.train_test_split(trainset_ratio=0.1)
X_total = X_total[:100, :]

reward_list = []
max_reward_list = []



checkpoint_load = True
checkpoint_epoch = 180
prec = 5
steps_on_memory = 200
total_steps = 10

blend_boundary = [-40, 10] #reward boundary of blending
blend_width = 5
NN_num = len(blend_boundary) + 1
actors = []
critics = []

for i in tqdm(range(X_total.shape[0])):
    #obs_lc_num = np.random.randint(merge_num)
    #obs_lc_time = np.argmax(X_total[i, lightcurve_unit_len*(obs_lc_num):lightcurve_unit_len*(obs_lc_num+1)])
    env = AstEnv(X_total[i, :-9*merge_num], X_total[i, -9*merge_num:], merge_num, N_set, lightcurve_unit_len)
    state_dim = (env.Ntheta//env.ast_obs_unit_step)*(env.Nphi//env.ast_obs_unit_step) + (lightcurve_unit_len//env.lc_obs_unit_step)
    n_actions = 4

    # config
    if i==0:
        for k in range(NN_num):
            actors.append(Actor(state_dim, n_actions, hidden_size=512, activation=nn.Tanh, prec=prec))
            critics.append(Critic(state_dim, hidden_size=512, activation=nn.Tanh))
                
        actor = NNBlender(actors, blend_boundary, blend_width)
        critic = NNBlender(critics, blend_boundary, blend_width)
        learner = A2CLearner(actor, critic, actor_lr=0.8e-4, critic_lr=0.8e-3)
    runner = Runner(env, prec)

    if i==0 and checkpoint_load:
        for k in range(NN_num):
            actor_checkpoint = torch.load(model_save_path+"actor"+str(k)+"_"+str(checkpoint_epoch)+".pt")
            actors[k].load_state_dict(actor_checkpoint['model_state_dict'])
            learner.actor_optim.load_state_dict(actor_checkpoint['optimizer_state_dict'])
            critic_checkpoint = torch.load(model_save_path+"critic"+str(k)+"_"+str(checkpoint_epoch)+".pt")
            critics[k].load_state_dict(critic_checkpoint['model_state_dict'])
            learner.critic_optim.load_state_dict(critic_checkpoint['optimizer_state_dict'])

    if env.ell_err:
        continue

    reward_past = 0
    for j in range(total_steps):
        memory, last_reward, reward_lists = runner.run(steps_on_memory, i+checkpoint_epoch, j, (reward_list, max_reward_list))
        reward_list = reward_lists[0]
        max_reward_list = reward_lists[1]
        learner.learn(memory, runner.steps, discount_rewards=True)

        if abs(last_reward - reward_past) < 1 and j != 0:
            break
        reward_past = last_reward + 0
        
        if (last_reward < -1.5e+2 and j >= 1) or runner.passed:
            break
        if (last_reward < 20 and j >= 6) or runner.passed:
            break
        
        if False and runner.passed:
            if env.obs_lc_num != 2:
                env.obs_lc_num = env.obs_lc_num + 1
            else:
                if runner.all_done:
                    break
                else:
                    env.obs_lc_num = 0

    # Chekcpoint
    if i%30 == 0:
        torch.save({
            'epoch':i,
            'model_state_dict':actor.state_dict(),
            'optimizer_state_dict':learner.actor_optim.state_dict()
        }, model_save_path+"actor_"+str(i+checkpoint_epoch)+".pt")

        torch.save({
            'epoch':i,
            'model_state_dict':critic.state_dict(),
            'optimizer_state_dict':learner.critic_optim.state_dict()
        }, model_save_path+"critic_"+str(i+checkpoint_epoch)+".pt")

        with open(model_save_path+"reward_list.txt", 'a+') as file:
            for item in reward_list:
                file.write(str(item)+",")

        with open(model_save_path+"max_reward_list.txt", 'a+') as file:
            for item in max_reward_list:
                file.write(str(item)+",")

plt.plot(reward_list)
plt.show()

plt.plot(max_reward_list)
plt.show()
    
